"""
Agent-authored skill semantic safety validator (Phase 3.17.2).

Semantic-layer safety checks that go beyond structural validation.
Validates that skill descriptions are honest, high-risk primitives
are not chained together, and inline code blocks are constrained.

Composed into ``SkillSafetyValidator`` during author-time validation.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.capabilities.skills.skill import CapabilitySkill


# ── High-risk primitive name patterns ──────────────────────────────────────
# Primitive names matching any of these substrings are considered high-risk.
# Chaining two or more high-risk primitives together in one skill is rejected.
HIGH_RISK_PATTERNS: set[str] = {
    "exec",
    "delete",
    "remove",
    "unlink",
    "rmdir",
    "chmod",
    "chown",
    "sudo",
    "install",
    "uninstall",
    "format",
    "truncate",
    "drop",
    "purge",
}

# ── Exfiltration chain patterns ───────────────────────────────────────────
# A skill that reads data AND sends it somewhere is an exfiltration risk.
_READ_PATTERNS = {"read", "get", "fetch", "list", "cat", "download"}
_SEND_PATTERNS = {"post", "send", "put", "upload", "publish", "push"}


# ── Embedded code limits ───────────────────────────────────────────────────
MAX_PYTHON_BLOCK_LINES = 50
MAX_PYTHON_BLOCK_CHARS = 2000
FORBIDDEN_PYTHON_TOKENS: set[str] = {
    "import ",
    "__import__",
    "exec(",
    "eval(",
    "compile(",
    "open(",
    "__builtins__",
    "subprocess",
    "os.",
    "sys.",
    "shutil",
    "pathlib",
}


class SkillSemanticSafetyValidator:
    """Validates semantic properties of agent-authored skills.

    Usage::

        sem = SkillSemanticSafetyValidator()
        result = sem.validate(skill)
        if not result.passed:
            raise ValueError("; ".join(result.errors))
    """

    def validate(self, skill: CapabilitySkill) -> "SafetyResult":
        """Run all semantic safety checks on *skill*."""
        from src.capabilities.registry.skill_safety import SafetyResult

        errors: list[str] = []

        errors.extend(self._check_description_fidelity(skill))
        errors.extend(self._check_high_risk_chains(skill))
        errors.extend(self._check_embedded_code(skill))

        return SafetyResult(passed=len(errors) == 0, errors=errors)

    # ── Individual checks ──────────────────────────────────────────────────

    def _check_description_fidelity(self, skill: CapabilitySkill) -> list[str]:
        """Check skill name and description are not misleading.

        Catches:
        - Empty or placeholder names (``"skill"``, ``"untitled"``, ``""``)
        - Names that claim to be something they're not (e.g. "safe-helper"
          but uses dangerous primitives)
        - Descriptions shorter than 10 chars (likely autogenerated filler)
        """
        errors: list[str] = []
        name = skill.manifest.name
        desc = skill.manifest.description

        # Empty / placeholder names
        if not name or not name.strip():
            errors.append("skill name is empty or whitespace-only")
        elif name.lower() in ("skill", "untitled", "new_skill", "new-skill", "myskill"):
            errors.append(
                f"skill name '{name}' is a placeholder — agent-authored "
                f"skills must have meaningful names"
            )

        # Empty / placeholder descriptions
        if not desc or not desc.strip():
            errors.append("skill description is empty")
        elif len(desc.strip()) < 10:
            errors.append(
                f"skill description is too short ({len(desc.strip())} chars) — "
                f"must be at least 10 characters"
            )

        # Misleading "safe" names with dangerous primitives
        safe_name_patterns = ("safe", "harmless", "benign", "readonly", "read-only")
        if any(p in name.lower() for p in safe_name_patterns):
            dangerous_prims = [
                p for p in skill.manifest.primitives
                if any(risk in p.lower() for risk in HIGH_RISK_PATTERNS)
            ]
            if dangerous_prims:
                errors.append(
                    f"skill name '{name}' implies safety but declares "
                    f"high-risk primitives: {dangerous_prims}"
                )

        return errors

    def _check_high_risk_chains(self, skill: CapabilitySkill) -> list[str]:
        """Check for chaining of high-risk primitives.

        Two rules:
        1. A single skill must not reference 2+ high-risk primitives.
        2. A skill must not pair a data-read primitive with a data-send
           primitive (potential exfiltration chain).
        """
        errors: list[str] = []
        declared = [p.lower() for p in skill.manifest.primitives]

        # Rule 1: 2+ high-risk primitives
        high_risk_found = [
            p for p in skill.manifest.primitives
            if any(pattern in p.lower() for pattern in HIGH_RISK_PATTERNS)
        ]
        if len(high_risk_found) >= 2:
            errors.append(
                f"skill chains {len(high_risk_found)} high-risk primitives "
                f"({high_risk_found}) — agent-authored skills may not chain "
                f"multiple high-risk operations"
            )

        # Rule 2: read + send = exfiltration risk
        has_read = any(any(p in prim.lower() for p in _READ_PATTERNS) for prim in declared)
        has_send = any(any(p in prim.lower() for p in _SEND_PATTERNS) for prim in declared)
        if has_read and has_send:
            errors.append(
                "skill combines data-read and data-send primitives — "
                "potential exfiltration chain is not allowed in "
                "agent-authored skills"
            )

        return errors

    def _check_embedded_code(self, skill: CapabilitySkill) -> list[str]:
        """Check inline Python blocks in steps are safe and bounded.

        Enforces:
        - Maximum line count (``MAX_PYTHON_BLOCK_LINES``)
        - Maximum character count (``MAX_PYTHON_BLOCK_CHARS``)
        - No forbidden tokens (import, exec, eval, subprocess, etc.)
        """
        errors: list[str] = []

        for i, step in enumerate(skill.manifest.steps):
            code = step.get("python")
            if code is None:
                continue

            code_str = str(code)
            lines = code_str.split("\n")

            # Size limits
            if len(lines) > MAX_PYTHON_BLOCK_LINES:
                errors.append(
                    f"step[{i}] python block is {len(lines)} lines — "
                    f"maximum is {MAX_PYTHON_BLOCK_LINES}"
                )
            if len(code_str) > MAX_PYTHON_BLOCK_CHARS:
                errors.append(
                    f"step[{i}] python block is {len(code_str)} chars — "
                    f"maximum is {MAX_PYTHON_BLOCK_CHARS}"
                )

            # Forbidden tokens
            for token in FORBIDDEN_PYTHON_TOKENS:
                if token in code_str:
                    errors.append(
                        f"step[{i}] python block contains forbidden token "
                        f"'{token}' — not allowed in agent-authored skills"
                    )

        return errors
